StaticServer:
  env: PROD

  https:
#    activate: true
#    http2: false
    privateKey: ../certificates/server.key
    certificate: ../certificates/server.crt

  Proxy:
    consoleUrl: https://localhost:3443
    strictSSL: false

  Frontend:
    publicUrl: https://localhost:3449
    port: 3449
